### ISSUE TITLE
Preview based on world name(?) leading to false previews

### ISSUE THREAD

**Issue by turnipjs** [DaDerpDuck/Seamless-Loading-Screen-Forge#1]
If you make a world called "new world" and then delete it, then make a different world called "new world" it will use the leftover preview from the original "new world".

**Comment by turnipjs** [comment]
Great mod though! It's a completely minor issue for an otherwise very cool mod!

**Comment by DaDerpDuck** [comment]
You are right that previews are saved with the world name. Reason's so that users could easily find the image file to copy it if they want to (located under the screenshots directory)
I'll fix this in the next update by removing the image save when its associated world is deleted. This'll only apply to singleplayer worlds, where deleting a world usually means you won't be able to come back to it. Thanks for the report!
