### ISSUE TITLE
optifine "Show FPS" is  visible in top left

### ISSUE THREAD

**Issue by ghost** [DaDerpDuck/Seamless-Loading-Screen-Forge#2]
the optifine "Show FPS" option is visible in the top left while joining server, either it gets captured in the screenshot or is running overtop the seamless loading screen for some reason

**Comment by DaDerpDuck** [comment]
So Optifine's FPS gui is drawn right after the ingame guis are rendered (hotbar, boss health, crosshair, etc.) There are two cases where ingame guis are rendered, and that is whether hideGUI is not enabled (F1) or if a screen is being displayed. Seamless Loading Screen works by displaying a new screen and, immediately when rendered, takes a screenshot of what is on the screen - therefore causing ingame guis being drawn. I solved the problem of vanilla ingame guis being displayed since Forge luckily has a cancelable event for them. Optifine, however, doesn't use the event, leading to the gui being captured in the screenshot.
This is a little bit of an Optifine issue so I'd suggest [opening an issue there too](https://github.com/sp614x/optifine/issues), but I can work around it by hooking into their classes. Thanks for the report though! Their lagometer also turns out to have the same problem too, so that's two issues and one stone lol

**Comment by ghost** [comment]
that was fast haha
